### ISSUE TITLE
bot.SimpleBot.execute

### ISSUE THREAD

**Issue by LunarArcanus** [bgw/python-ircutils#4]
Hello, I'm having an issue with the execute() method.

Upon joining (and creating, so that it is the operator) a channel, the bot is supposed to set the topic of the channel.

Example from the docs:
> self.execute("PRIVMSG", channel, trailing="Hello, world!")

I'm doing
```python
self.execute("TOPIC", channel="#chan", trailing="Blah")
```
and tried:
```python
self.execute("TOPIC", trailing="#chan Blah")
```
but neither is working.

Same issue when trying to set the +B usermode for the bot (in the on_welcome handler):
```python
self.execute("MODE", trailing="%s +B" %self.nickname)
```
Am I doing something wrong, perhaps?

**Comment by bgw** [comment]
I think the only keyword argument supported by that function is `trailing`, and the rest are positional arguments. Try

```python
self.execute("TOPIC", "#chan", trailing="Blah")
```

**FYI**: I didn't develop this library, rather I forked it and patched in python 3 and unicode support (see the other two branches), though it [seems like the previous developer isn't maintaining this anymore either](http://www.dev.guardedcode.com/projects/ircutils/). That said, I'm willing to help work though problems.

**Comment by Kopachris** [comment]
As @bgw says, the only keyword argument supported by `Connection.execute()` is `trailing`. Per the RFC, a trailing parameter (if present) is prefixed with a colon by `ircutils` and placed after any other parameters. The answer @bgw gave should work for TOPIC.

The MODE command, on the other hand, does not support a trailing parameter. All of its parameters are positional, as defined by the RFC: https://tools.ietf.org/html/rfc1459#section-4.2.3

The code you would want for that is `self.execute('MODE', self.nickname, '+B')`

**Comment by bgw** [comment]
@Kopachris, do you want to take control of this repository? I don't really have an interest in maintaining it, though I'm willing to help with the occasional usage question. I can transfer it over to you.

**Comment by Kopachris** [comment]
@bgw Uh... okay! To be honest, I 1) thought you had abandoned it as well, and 2) didn't notice that you had been working in pipeep-patch-set instead of master. I already forked master into [ircutils3](https://github.com/Kopachris/python-ircutils) to work on Python 3 support (along with some minor changes to make it work better with a bot I'm working on) some time ago.

In any case, I'd be happy to take control and work on merging the two.

**Comment by bgw** [comment]
@Kopachris, Great. I can't transfer it if you already have a fork with the same name. Can you temporarily delete your repository so I can transfer it? Then you can push your local copy back on top of the remote.

**Comment by Kopachris** [comment]
Done.

**Comment by LunarArcanus** [comment]
This did the trick. Thank you very much, @bgw and @Kopachris ! ^_^

**Comment by bgw** [comment]
@Kopachris, I made the request to move the repo, but you need to accept it on your end.

**Comment by Kopachris** [comment]
Cool. Seeing as I've been up for about 20 hours now, I'll wait until tomorrow to start work on it.

@LunarArcanus you're welcome. :smile:

**Comment by bgw** [comment]
@Kopachris Thanks!

@LunarArcanus glad we could help!
